-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Projects Table
create table if not exists projects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  description text,
  thumbnail text,
  type text check (type in ('script', 'audio', 'image', 'video', 'complete')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Scenes Table
create table if not exists scenes (
  id bigint generated by default as identity primary key,
  project_id uuid references projects(id) on delete cascade not null,
  scene_order integer not null,
  text text not null,
  audio_url text,
  image_url text,
  video_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table projects enable row level security;
alter table scenes enable row level security;

-- RLS Policies for Projects
create policy "Users can view their own projects"
  on projects for select
  using (auth.uid() = user_id);

create policy "Users can insert their own projects"
  on projects for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own projects"
  on projects for update
  using (auth.uid() = user_id);

create policy "Users can delete their own projects"
  on projects for delete
  using (auth.uid() = user_id);

-- RLS Policies for Scenes
create policy "Users can view scenes of their projects"
  on scenes for select
  using (
    exists (
      select 1 from projects
      where projects.id = scenes.project_id
      and projects.user_id = auth.uid()
    )
  );

create policy "Users can insert scenes to their projects"
  on scenes for insert
  with check (
    exists (
      select 1 from projects
      where projects.id = scenes.project_id
      and projects.user_id = auth.uid()
    )
  );

create policy "Users can update scenes of their projects"
  on scenes for update
  using (
    exists (
      select 1 from projects
      where projects.id = scenes.project_id
      and projects.user_id = auth.uid()
    )
  );

create policy "Users can delete scenes of their projects"
  on scenes for delete
  using (
    exists (
      select 1 from projects
      where projects.id = scenes.project_id
      and projects.user_id = auth.uid()
    )
  );
