'use client';

import { Modal } from '@/components/ui/Modal';
import { Download, Share2 } from 'lucide-react';

interface VideoResultModalProps {
    isOpen: boolean;
    onClose: () => void;
    videoUrl: string;
}

export function VideoResultModal({ isOpen, onClose, videoUrl }: VideoResultModalProps) {
    return (
        <Modal isOpen={isOpen} onClose={onClose} title="비디오 상세" className="w-[800px]">
            <div className="flex flex-col gap-5">
                <div className="aspect-video bg-black rounded-lg overflow-hidden flex items-center justify-center border border-[#2a2a35]">
                    <video controls autoPlay loop className="max-w-full max-h-[60vh]">
                        <source src={videoUrl} type="video/mp4" />
                        Your browser does not support the video tag.
                    </video>
                </div>

                <div className="flex justify-between items-center pt-2">
                    <div className="flex flex-col gap-1">
                        <span className="text-sm text-[#a0a0b0]">Generated by KIE AI</span>
                    </div>
                    <div className="flex gap-3">
                        <button className="px-4 py-2 rounded-md border border-[#383845] text-[#a0a0b0] hover:text-white hover:border-white transition-colors text-sm flex items-center gap-2">
                            <Share2 className="w-4 h-4" />
                            공유
                        </button>
                        <button className="px-4 py-2 rounded-md bg-(--primary-color) text-white hover:bg-[#4a4ddb] transition-colors text-sm flex items-center gap-2 font-medium">
                            <Download className="w-4 h-4" />
                            다운로드
                        </button>
                    </div>
                </div>
            </div>
        </Modal>
    );
}
