'use client';

import { Modal } from '@/components/ui/Modal';
import { Download, Share2 } from 'lucide-react';

interface ImageResultModalProps {
    isOpen: boolean;
    onClose: () => void;
    imageUrl: string;
}

export function ImageResultModal({ isOpen, onClose, imageUrl }: ImageResultModalProps) {
    return (
        <Modal isOpen={isOpen} onClose={onClose} title="이미지 상세" className="w-[800px]">
            <div className="flex flex-col gap-5">
                <div className="aspect-video bg-black rounded-lg overflow-hidden flex items-center justify-center border border-[#2a2a35]">
                    <img src={imageUrl} alt="Generated" className="max-w-full max-h-[60vh] object-contain" />
                </div>

                <div className="flex justify-between items-center pt-2">
                    <div className="flex flex-col gap-1">
                        <span className="text-sm text-[#a0a0b0]">Generated by Fal.ai FLUX.1</span>
                    </div>
                    <div className="flex gap-3">
                        <button className="px-4 py-2 rounded-md border border-[#383845] text-[#a0a0b0] hover:text-white hover:border-white transition-colors text-sm flex items-center gap-2">
                            <Share2 className="w-4 h-4" />
                            공유
                        </button>
                        <button className="px-4 py-2 rounded-md bg-(--primary-color) text-white hover:bg-[#4a4ddb] transition-colors text-sm flex items-center gap-2 font-medium">
                            <Download className="w-4 h-4" />
                            다운로드
                        </button>
                    </div>
                </div>
            </div>
        </Modal>
    );
}
